version: '3.8'
services:
  nginx-entrypoint:
    image: nginx-custom:latest 
    restart: always 
    ports:
      - "8080:80" 
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html 
      - ./conf:/etc/nginx/conf.d 
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private 
