---

- name: Install Nginx and upload my page
  hosts: localhost
  become: yes


  vars:
   # source_folder: /html
    dest_folder  : /var/www/html/

  tasks:

  - name: Update apt cache
    apt: update_cache=yes

  - name: Install required packages
    apt: name=nginx state=latest

  - name: Start Web Server
    service: name=nginx state=started enabled=yes

  - name: Check 80 port
    wait_for:
     port: 80
     timeout: 60

  - name: Copy MyPage file to Web Server
    template:
     src: ./index.html
     dest: "{{ dest_folder }}" 
    notify: Restart nginx
  
  - name: Copy configuration files
    template:
     src: ./nginx.conf
     dest: /etc/nginx/conf.d/
    notify: Restart nginx

  handlers:
  - name: Restart nginx
    service: name=nginx state=restarted
