---

- name: Install Nginx and upload my page
  hosts: all
  become: yes


  vars:
    source_folder: /etc/ansible/
    dest_folder  : /var/www/html/
    dest_cert    : /etc/nginx/ssl/

  tasks:

  - name: Update apt cache
    apt: update_cache=yes

  - name: Install required packages
    apt: name=nginx state=latest

  - name: Start Web Server
    service: name=nginx state=started enabled=yes

  - name: Check 80 port
    wait_for:
     port: 80
     timeout: 60

  - name: Copy MyPage file to Web Server
    template:
     src: "{{ source_folder }}" 
     dest: "{{ dest_folder }}" 
    notify: Restart nginx
  
  - name: Copy configuration files
    template:
     src: ./html/nginx.conf
     dest: /etc/nginx/nginx.conf
    notify: Restart nginx

  - name: Copy cert
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - {src: {{ source_folde

  handlers:
  - name: Restart nginx
    service: name=nginx state=restarted
