name: Local Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
	
     - name: Print start pipelinde
       run: echo "Этап сборки - создание Docker конейнера..."
  
     - name: Build Docker image
       run: docker build -t sug/myserver:latest .
      

#      - name: Docker build
#        run: docker build -t sug/myserver:latest .

     - name: Print end docker build
       run: echo "Сборка завершена и Docker контейнер создан."
      
    -  name: Print Happy Message for CI finish
       run: echo "CI Pipeline part Finished successfully"
