name: Publish to server

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myserver:latest

      
  
  server_update:
    needs: push_to_registry
    name: Update server buy ssh
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER_LOGIN }}
          key: ${{ secrets.SERVER_USER_KEY }}
          #script_stop: true
          script: |
           echo "Stop container"
           sudo docker stop leopard >> /dev/null
           sudo docker rm leopard >> /dev/null
           sudo docker image rm sureiger/myserver
           echo "Pull  image"
           sudo docker pull sureiger/myserver
           echo "Start leopard container"
           sudo docker run --name leopard -d -p 80:80 -p 443:443 sureiger/myserver >> /dev/null
           echo "Finish deploying!"
